CREATE TABLE policeRecord.Criminal(
ID INT NOT NULL AUTO_INCREMENT,
CriminalNUM VARCHAR(10) UNIQUE NOT NULL,
PersonID INT,
CONSTRAINT PK_Criminal_ID PRIMARY KEY(ID),
CONSTRAINT FK_Person_ID FOREIGN KEY (PersonID) REFERENCES Person(ID)
);