CREATE TABLE policeRecord.PoliceOfficer(
ID INT NOT NULL AUTO_INCREMENT,
OfficerBadgeNUM VARCHAR(10) UNIQUE NOT NULL,
OfficerRank VARCHAR(10),
PersonID INT,
DepartmentID INT,
CONSTRAINT PK_Officer_ID PRIMARY KEY(ID),
CONSTRAINT FK_Officer_ID FOREIGN KEY (PersonID) REFERENCES Person(ID),
CONSTRAINT FK_Department_ID FOREIGN KEY (DepartmentID) REFERENCES Department(ID)
);